name: Percy visual tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          install: false
          start: npm start
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          command-prefix: "percy exec -- npx"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
