name: Percy visual tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
          command: "cypress run"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
